### ISSUE TITLE
Path argument is ignored when passing a config file

### ISSUE THREAD

**Issue by g0di** [hadialqattan/pycln#94]
Hello,

Running `pycln` with only a config file as CLI options seems to ignore the `path` specifiied in the provided config file

**To reproduce**
According to the following `pyproject.toml` file
```toml
[tool.pycln]
path = "/user_management_rest_api/"
```

Running following command
```bash
pycln --config pyproject.toml
```
Produce the following output
```
No Path provided. Nothing to do 😴
```

While I expected `pycln` to run over `/user_management_rest_api/` folder specified in provided config file

>I tried to set `verbose = true` in my `pyproject.toml` file to ensure it was loaded and it worked as expected. Just the `path` looks like to be somehow ignored

**Environment**

- Python Version: 3.7
- Pycln Version: 1.1.0
- OS Type: [e.g.macOS Big Sur]

**Comment by hadialqattan** [comment]
Hi @g0di, after doing some investigation I found that this problem is related to `Config` class:
https://github.com/hadialqattan/pycln/blob/9ed66c98ba1b9d64489d7e388755877b48662997/pycln/utils/config.py#L26-L39

(on `Config` we have `"paths"` attr while in the config file(s) we use `"path"`)

also, I used `hasattr` for validating the config keys which returns `False` when the key is `"path"` (so `"path"` value will be ignored):
https://github.com/hadialqattan/pycln/blob/9ed66c98ba1b9d64489d7e388755877b48662997/pycln/utils/config.py#L152-L160

---

anyway, thank you for reporting this bug. I'm gonna fix it as soon as possible.

**Comment by g0di** [comment]
Thank you for your feedback ;)
